#!/bin/sh
. "$(dirname -- "${0}")/_/husky.sh"

# Cores
NC='\033[0m'
BRed='\033[1;31m'

REGEX_ISSUE_ID="[a-zA-Z0-9,.\\_\\-]+-[0-9]+"
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
ISSUE_ID=$(echo "$BRANCH_NAME" | grep -o -E "$REGEX_ISSUE_ID")

if [ -z "$ISSUE_ID" ]; then
    echo -e "${BRed}Branch não está no padrão que deveria mestre... ${NC}"
    exit 1
fi

# Verifica se a última linha do commit contém o ID da issue
if ! tail -n 1 "$1" | grep -q "$ISSUE_ID"; then
    echo "$ISSUE_ID: $(cat "$1")" > "$1"
fi
